# Generated by Django 5.2.7 on 2025-12-18 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_brand_alter_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
            ],
            options={
                'verbose_name': 'Отчет и аналитика',
                'verbose_name_plural': 'Отчеты и аналитика',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.product',),
        ),
    ]
