# Generated by Django 5.2.7 on 2025-12-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_analyticsreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyticsReport',
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Отчет и аналитика', 'verbose_name_plural': 'Отчет и аналитика'},
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='Не указано', max_length=200, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Банковская карта'), ('cash', 'Наличные курьеру'), ('transfer', 'Банковский перевод'), ('sbp', 'СБП')], default='card', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
