# Generated by Django 5.2.7 on 2026-04-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_delete_analyticsreport_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Новичок'), ('amateur', 'Любитель'), ('professional', 'Профессионал')], max_length=20, null=True, verbose_name='Уровень подготовки'),
        ),
    ]
